# Generated by Django 5.1.6 on 2025-02-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='images/news_default.png', upload_to='images/')),
            ],
        ),
    ]
